name: build
on:
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [macos, windows]
        include:
          - build: macos
            os: macos-latest
            rust: nightly
            target: x86_64-apple-darwin
            archive-name: rgrep-macos
          - build: windows
            os: windows-2019
            rust: nightly-x86_64-msvc
            target: x86_64-pc-windows-msvc
            archive-name: rgrep-windows.exe
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0

      - name: gotidy
        run: 
          go mod tidy
      - name: bu
        run:
          go build -o ${{ matrix.archive-name }} ./cmd/fynedemo

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cd archive
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "./cmd/fynedemo/${{ matrix.archive-name }}" ./
          else
            cp "./cmd/fynedemo/${{ matrix.archive-name }}" ./
          fi
      - name: Upload archive
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.archive-name }}
          path: archive/${{ matrix.archive-name }}
